name: "Unit Tests"

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches:
        - '*'

jobs:
  build:
    name: "Unit Tests on Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: npm install
      - run: npm test
